# Generated by Django 5.0.3 on 2024-05-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_initial'),
    ]

    operations = [
    ]
