# Generated by Django 5.0.3 on 2024-06-02 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20240531_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id_additive', models.AutoField(primary_key=True, serialize=False)),
                ('additive_name', models.CharField(max_length=50)),
                ('additive_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id_broker', models.AutoField(primary_key=True, serialize=False)),
                ('broker_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_centro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_Group',
            fields=[
                ('id_commodity_group', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_Subtype',
            fields=[
                ('id_commodity_subtype', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_subtype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_Type',
            fields=[
                ('id_commodity_type', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id_counterparty', models.AutoField(primary_key=True, serialize=False)),
                ('counterparty_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty_Facility',
            fields=[
                ('id_counterparty_facility', models.AutoField(primary_key=True, serialize=False)),
                ('counterparty_facility_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id_currency', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Format',
            fields=[
                ('id_delivery_format', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_format_name', models.CharField(max_length=50)),
                ('delivery_format_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ICOTERM',
            fields=[
                ('id_icoterm', models.AutoField(primary_key=True, serialize=False)),
                ('icoterm_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sociedad',
            fields=[
                ('id_sociedad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sociedad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trade_Operation_Type',
            fields=[
                ('id_trade_operation_type', models.AutoField(primary_key=True, serialize=False)),
                ('trade_operation_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id_trader', models.AutoField(primary_key=True, serialize=False)),
                ('trader_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcryptocurrency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id_commodity', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_name_short', models.CharField(max_length=50)),
                ('commodity_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.commodity_group')),
                ('commodity_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.commodity_subtype')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.commodity_type')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('broker_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrega', models.CharField(max_length=50)),
                ('freight_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forex', models.DecimalField(decimal_places=4, max_digits=10)),
                ('payment_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_period', models.DateField()),
                ('date', models.DateField()),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.additive')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.broker')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.commodity')),
                ('commodity_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.commodity_group')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.centro')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.counterparty')),
                ('broker_fee_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_fee_contracts', to='webapp.currency')),
                ('trade_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_contracts', to='webapp.currency')),
                ('delivery_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.delivery_format')),
                ('icoterm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.icoterm')),
                ('sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.sociedad')),
                ('trade_operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.trade_operation_type')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.trader')),
            ],
        ),
    ]
